name: Build Deimos

on:
  push:
    paths:
      - 'buildversion.txt'
    branches: [ "buildtest" ]
  pull_request:
    paths:
      - 'buildversion.txt'
    branches: [ "buildtest" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: buildtest
          
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
          cache: pip
        
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
          
      - name: Install pyinstaller
        run: python -m pip install pyinstaller==5.1
        
      - name: Run pyinstaller
        run: pyinstaller --onefile --icon=Deimos-logo.ico ./Deimos.py
        
      - name: Copy exe
        run: xcopy /y '.\dist\Deimos.exe' '.\Deimos.exe'
      
      - name: Update version file
        run: xcopy /y buildversion.txt LatestVersion.txt

      - name: Cleanup
        run: |
          rm -r -fo dist
          rm -r -fo build
          rm Deimos.spec
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name = "Github Action"
          git add .
          git commit -a -m "Build Deimos"
          
      - name: Push changes
        if: ${{ success() }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: buildtest
          github_token: ${{ secrets.GITHUB_TOKEN }}
